name: Secrets sync

on:
  workflow_dispatch:
  schedule:
  - cron: "*/10 * * * *"

jobs:
  sync-secrets:
    name: Syncing secrets
    runs-on: ubuntu-latest
    steps:
    - uses: google/secrets-sync-action
      with:
        SECRETS: |
          WORKFLOW_AUTH
          WAKATIME_API_KEY
        REPOSITORIES: |
          shrivastava-prateek
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_SECRETS }}
        CONCURRENCY: 10
      env:
        JOB_RUN_ID: ${{github.run_id}}
