name: Secrets sync

on:
  workflow_dispatch:
  schedule:
  - cron: "*/10 * * * *"

jobs:
  sync-secrets:
    name: Syncing secrets
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            ^WORKFLOW_+
            ^WAKATIME_+
            ^SYNC_+
          REPOSITORIES: |
            shrivastava-prateek/shrivastava-prateek
            shrivastava-prateek/shrivastava-prateek.github.io
          GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
          CONCURRENCY: 10
          REPOSITORIES_LIST_REGEX: false
        env:
          JOB_RUN_ID: ${{github.run_id}}
